name: PHP Composer

on: pull_request

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Install Composer
      working-directory: ./src
      run: composer install
    
    - name: Run PhpStan
      working-directory: ./src
      run: vendor/bin/phpstan analyse -l 8 app --error-format=github --memory-limit=1G
  
  lint:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Install Composer
      working-directory: ./src
      run: composer install
    
    - name: lint
      working-directory: ./src
      run: vendor/bin/phpcs --standard=phpcs.xml ./
