name: PHP Composer

on: pull_request

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Run PhpStan
      working-directory: ./src
      run: vendor/bin/phpstan analyse app --error-format=github
