name: PHPStan

on: [push, pull_request]

jobs:
  phpstan:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: composer install
    - name: Run PHPStan
      run: vendor/bin/phpstan analyse --configuration phpstan.neon
